// Generated by Wrangler by running `wrangler types`

interface Env {
  VITE_API_URL: string
  DATABASE_URL: string
  CLIENT_URL: string
  GOOGLE_CLIENT_ID: string
  GOOGLE_CLIENT_SECRET: string
  SESSION_SECRET: string
  AUTHORIZED_EMAIL: string
  NODE_ENV: string
  JWT_SECRET: string
  R2: R2Bucket
  DB: D1Database
}
