name = "my-remix-app"
compatibility_date = "2024-11-12"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./build/client"

[[d1_databases]]
binding = "DB"
database_name = "gourmet-report"
database_id = "94e8f7da-ec83-4d56-8014-1069bc567280"
