name = "my-remix-app"
compatibility_date = "2024-11-12"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./build/client"

[[d1_databases]]
binding = "DB"
database_name = "gourmet-report"
database_id = "b21b757e-ec73-42c3-a95d-c0a7d9b459c0"
